name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ run_cypress_tests ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Install Cypress (if not in package.json)
        run: npx cypress install

      - name: Show project file structure (debug)
        run: find . -type f

      - name: Run Cypress Tests
        run: npx cypress run
